import 'dart:typed_data';
import 'package:flutter/material.dart';

enum AccountType { standard, vip }

extension AccountTypeLimits on AccountType {
  /// Nombre maximal de spectateurs autorisé pour ce type de compte.
  int get maxViewers => switch (this) {
        AccountType.standard => 150,
        AccountType.vip => 100000,
      };
}

class UserProfile {
  final String username;
  final Color color;
  final int? avatarIndex;

  const UserProfile({required this.username, required this.color, this.avatarIndex});
}

const profiles = [
  UserProfile(username: 'alex_brt',    color: Colors.pinkAccent,      avatarIndex: 12),
  UserProfile(username: 'Sarah_M',     color: Colors.cyanAccent,       avatarIndex: 45),
  UserProfile(username: 'jo_99',       color: Colors.yellowAccent,     avatarIndex: null),
  UserProfile(username: 'YukiChan',    color: Colors.purpleAccent,     avatarIndex: 78),
  UserProfile(username: 'devmaster42', color: Colors.greenAccent,      avatarIndex: 130),
  UserProfile(username: 'CoolKid',     color: Colors.orangeAccent,     avatarIndex: null),
  UserProfile(username: 'nightowl__',  color: Colors.lightBlueAccent,  avatarIndex: 200),
  UserProfile(username: 'StarGazer',   color: Colors.tealAccent,       avatarIndex: 33),
  UserProfile(username: 'tech_fan',    color: Colors.pinkAccent,       avatarIndex: 99),
  UserProfile(username: 'MusicLvr',    color: Colors.cyanAccent,       avatarIndex: null),
  UserProfile(username: 'xXDarkXx',   color: Colors.purpleAccent,     avatarIndex: 150),
  UserProfile(username: 'flutterfan', color: Colors.greenAccent,      avatarIndex: 17),
  UserProfile(username: 'Watcher99',   color: Colors.orangeAccent,     avatarIndex: 210),
  UserProfile(username: 'lila_r',      color: Colors.yellowAccent,     avatarIndex: null),
  UserProfile(username: 'mo_streams',  color: Colors.lightBlueAccent,  avatarIndex: 64),
  UserProfile(username: 'Lucas_off',   color: Colors.tealAccent,       avatarIndex: 188),
  UserProfile(username: 'noemie.live', color: Colors.pinkAccent,       avatarIndex: 7),
  UserProfile(username: 'raptor77',    color: Colors.cyanAccent,       avatarIndex: null),
  UserProfile(username: 'Clem_B',      color: Colors.orangeAccent,     avatarIndex: 240),
  UserProfile(username: 'kev_gaming',  color: Colors.greenAccent,      avatarIndex: 55),
  UserProfile(username: 'ZoeR',        color: Colors.purpleAccent,     avatarIndex: null),
  UserProfile(username: 'theovlive',   color: Colors.yellowAccent,     avatarIndex: 120),
];

class ChatMessage {
  final String username;
  final String text;
  final Color color;
  final bool isOwn;
  final int? avatarIndex;
  final Uint8List? avatarBytes;

  const ChatMessage({
    required this.username,
    required this.text,
    required this.color,
    this.isOwn = false,
    this.avatarIndex,
    this.avatarBytes,
  });
}

final List<String> simulatedMessages = [
  '🔥🔥🔥',
  'Trop bien !',
  'Bonjour depuis Paris !',
  'Premier !',
  'C\'est incroyable',
  'Tu nous vois ?',
  '❤️❤️',
  'Trop fort',
  'Super stream',
  'Allez !!!',
  'Salut tout le monde !',
  '👋',
  'Magnifique !',
  'Encore !',
  'GG',
  '🎉🎉🎉',
  'oh là là',
  'meilleur live ever',
  '💯💯',
  'trop drôle',
  'j\'adore ce live',
  'continuez comme ça !',
  'trop stylé 😍',
  'coucou de Lyon !',
  'qui regarde depuis le Canada ?',
  'mdrrr',
  '😂😂😂',
  'tu fais quoi ce soir ?',
  'sérieux trop drôle ce live',
  'on t\'aime !!',
  'go go go',
  'il est où le son ?',
  'chante un peu stp',
  'ça fait plaisir de te voir',
  'wesh tout le monde',
  'je découvre, c\'est cool',
  'abonné direct',
  '🥹🥹',
  'tu peux refaire ça ?',
  'la vache, niveau !',
  'plus fort le son !',
  'merci pour le live',
  'salut la team',
  'tu nous manquais',
  'c\'est qui en arrière plan ? mdr',
  '👀👀',
  'on est combien là ?',
  'bisous depuis Marseille',
  'franchement gg',
  'tu restes encore un peu ?',
  'j\'ai mis un cadeau, tu l\'as vu ?',
  'reste authentique stp',
  'pause clope et on revient 😅',
  '🙌🙌',
  'tu vises quoi comme objectif ce soir ?',
  'allez un petit don pour la route',
  'je capte mal mais sinon top',
  'fan numéro 1 ici',
  'PTDR',
  'trop relou les pubs avant',
  '🥳🥳🥳',
  'le setup est propre',
  'c\'est nouveau ce filtre ?',
  'salut depuis la Belgique 🇧🇪',
  'on veut un cover !',
  'la qualité est top aujourd\'hui',
  'ça part en live de fou',
  'team présente !',
  'merci merci merci',
  '😍😍😍',
  'c\'est reparti pour un tour',
  'hello depuis Toulouse',
  'tu fais des lives souvent ?',
  'ça envoie du lourd',
  '🤩🤩',
  'jamais raté un live',
  'tu réponds aux questions ?',
  'le filtre te va trop bien',
  'on a besoin de toi ce soir',
  'ambiance de fou ici',
  'mes potes vont pas me croire',
  'présent !!',
  'tu tiens combien de temps en live ?',
  'la lumière est top',
  'ça déconne le son chez moi',
  '🫶🫶',
  'on veut une dédicace',
  'chuis venu juste pour toi',
  'good vibes ce soir',
  'tu connais cette chanson ?',
  'mode boost activé',
  'tkt on est là',
  'on monte en viewers !!',
  'GG la team',
  'attends je note ça',
  'belle énergie aujourd\'hui',
  '🔥👏',
  'encore un peu stp',
  'je relance le live',
  'salut depuis le Québec 🇨🇦',
  'comment tu fais ça ?!',
  'ça donne envie',
  'mood du soir',
  '🥶🥶',
  'restez motivés !',
  'allez on lâche rien',
  'top contenu comme toujours',
  'je viens de m\'abonner !',
  'la hype monte',
  'au top !!!',
  'salut depuis Bordeaux',
  'qui d\'autre regarde en cours mdr',
  'tu prends des pauses ?',
  '😤😤',
  'ça c\'est du contenu',
  'on est chauds !!',
  'tu fais une suite après ?',
  'le décor a changé non ?',
  'ptdrrr arrête',
  'merci pour ce moment',
  '🤍🤍',
  'tu viens d\'où à la base ?',
  'ambiance trop cool',
  'je sature de rire',
  'ça fait du bien ce live',
  'on croit en toi',
  'restons connectés',
  'tu lis vraiment tous les messages ?',
  'GG continue comme ça',
  '🌟🌟',
  'salut depuis Genève 🇨🇭',
  'le mic grésille un peu',
  'on attendait ça',
  'tu commences à quelle heure d\'habitude ?',
  'team motivée',
  'incroyable franchement',
  'ça monte en intensité',
  'tu tiens le rythme bravo',
  '👏👏👏',
  'je partage à mes potes',
  'salut depuis Nice',
  'c\'est la fête ici',
  'tu nous fais un signe ?',
  'au taquet',
  'top du top',
  '🚀🚀',
  'ça envoie sévère',
  'je note tout ce que tu dis',
  'on lâche pas l\'affaire',
  'salut depuis Strasbourg',
  'on est en feu ce soir',
  'tu fais quoi comme musique en fond ?',
  '🤝🤝',
  'big up depuis le boulot',
  'ça chauffe dans le chat',
  'tu réagis à ça ?',
  'jamais déçu',
  'c\'est validé',
  'restons dans le vibe',
  'merci pour la bonne humeur',
  '🎶🎶',
  'tu fais ça depuis longtemps ?',
  'salut depuis Lille',
  'ambiance de ouf',
  'je kiffe grave',
  'reste connecté avec nous',
  'GG les gars du chat aussi',
  '😎😎',
  'ça part en n\'importe quoi mdrr',
  'tu nous fais un tour de la pièce ?',
  'on suit à fond',
  'incroyable cette énergie',
  'salut depuis Rennes',
  'tu réponds en vocal ?',
  'tout le monde est chaud',
  'bravo pour la régularité',
  '🥇🥇',
  'le chat va trop vite',
  'je relis pas tout mais bravo',
  'salut depuis Nantes',
  'continue, c\'est génial',
  'on se retrouve demain ?',
  'tu fais une pause musique ?',
  '💪💪',
  'GG à toute la team présente',
  'ça reste un super moment',
  'salut depuis Montpellier',
  'tu vas faire combien de temps ce soir ?',
  '🤗🤗',
  'le live le plus fou de la semaine',
  'ça booste le moral',
  'on est trop bien là',
  'tu connais cette référence ?',
  'salut depuis Dijon',
  'arrête tu vas me faire pleurer',
  'team au complet ici',
  'GG pour le setup',
  '🌈🌈',
  'tu prends des questions ?',
  'on est fan du concept',
  'salut depuis Tours',
  'ça donne la pêche',
  'restons unis',
  'merci pour cette soirée',
  'tu fais un récap après ?',
  '😇😇',
  'salut depuis Reims',
  'on revient demain promis',
  'c\'est carrément ouf',
  'tu gères trop bien le chat',
  'on adore le rythme',
  '🙏🙏',
  'salut depuis Angers',
  'ça vaut le détour',
  'tu nous diras la suite ?',
  'top niveau ce soir',
  'on est hyper motivés',
  'GG pour la persévérance',
  '🎯🎯',
  'salut depuis Le Havre',
  'jamais vu un live aussi cool',
  'ça reste gravé',
  'merci pour tout',
  'à très vite !',
  'salut depuis Paris',
  'coucou de Paris',
  'Paris dans la place !',
  'présent depuis Paris',
  'on regarde depuis Paris',
  'team Paris 👋',
  'ça vient de Paris !',
  'hello depuis Paris',
  'fan venu de Paris',
  'Paris représente !',
  'salut depuis Lyon',
  'coucou de Lyon',
  'Lyon dans la place !',
  'présent depuis Lyon',
  'on regarde depuis Lyon',
  'team Lyon 👋',
  'ça vient de Lyon !',
  'hello depuis Lyon',
  'fan venu de Lyon',
  'Lyon représente !',
  'salut depuis Marseille',
  'coucou de Marseille',
  'Marseille dans la place !',
  'présent depuis Marseille',
  'on regarde depuis Marseille',
  'team Marseille 👋',
  'ça vient de Marseille !',
  'hello depuis Marseille',
  'fan venu de Marseille',
  'Marseille représente !',
  'salut depuis Toulouse',
  'coucou de Toulouse',
  'Toulouse dans la place !',
  'présent depuis Toulouse',
  'on regarde depuis Toulouse',
  'team Toulouse 👋',
  'ça vient de Toulouse !',
  'fan venu de Toulouse',
  'Toulouse représente !',
  'coucou de Nice',
  'Nice dans la place !',
  'présent depuis Nice',
  'on regarde depuis Nice',
  'team Nice 👋',
  'ça vient de Nice !',
  'hello depuis Nice',
  'fan venu de Nice',
  'Nice représente !',
  'coucou de Nantes',
  'Nantes dans la place !',
  'présent depuis Nantes',
  'on regarde depuis Nantes',
  'team Nantes 👋',
  'ça vient de Nantes !',
  'hello depuis Nantes',
  'fan venu de Nantes',
  'Nantes représente !',
  'coucou de Strasbourg',
  'Strasbourg dans la place !',
  'présent depuis Strasbourg',
  'on regarde depuis Strasbourg',
  'team Strasbourg 👋',
  'ça vient de Strasbourg !',
  'hello depuis Strasbourg',
  'fan venu de Strasbourg',
  'Strasbourg représente !',
  'coucou de Montpellier',
  'Montpellier dans la place !',
  'présent depuis Montpellier',
  'on regarde depuis Montpellier',
  'team Montpellier 👋',
  'ça vient de Montpellier !',
  'hello depuis Montpellier',
  'fan venu de Montpellier',
  'Montpellier représente !',
  'coucou de Bordeaux',
  'Bordeaux dans la place !',
  'présent depuis Bordeaux',
  'on regarde depuis Bordeaux',
  'team Bordeaux 👋',
  'ça vient de Bordeaux !',
  'hello depuis Bordeaux',
  'fan venu de Bordeaux',
  'Bordeaux représente !',
  'coucou de Lille',
  'Lille dans la place !',
  'présent depuis Lille',
  'on regarde depuis Lille',
  'team Lille 👋',
  'ça vient de Lille !',
  'hello depuis Lille',
  'fan venu de Lille',
  'Lille représente !',
  'coucou de Rennes',
  'Rennes dans la place !',
  'présent depuis Rennes',
  'on regarde depuis Rennes',
  'team Rennes 👋',
  'ça vient de Rennes !',
  'hello depuis Rennes',
  'fan venu de Rennes',
  'Rennes représente !',
  'coucou de Reims',
  'Reims dans la place !',
  'présent depuis Reims',
  'on regarde depuis Reims',
  'team Reims 👋',
  'ça vient de Reims !',
  'hello depuis Reims',
  'fan venu de Reims',
  'Reims représente !',
  'coucou de Le Havre',
  'Le Havre dans la place !',
  'présent depuis Le Havre',
  'on regarde depuis Le Havre',
  'team Le Havre 👋',
  'ça vient de Le Havre !',
  'hello depuis Le Havre',
  'fan venu de Le Havre',
  'Le Havre représente !',
  'salut depuis Saint-Étienne',
  'coucou de Saint-Étienne',
  'Saint-Étienne dans la place !',
  'présent depuis Saint-Étienne',
  'on regarde depuis Saint-Étienne',
  'team Saint-Étienne 👋',
  'ça vient de Saint-Étienne !',
  'hello depuis Saint-Étienne',
  'fan venu de Saint-Étienne',
  'Saint-Étienne représente !',
  'salut depuis Toulon',
  'coucou de Toulon',
  'Toulon dans la place !',
  'présent depuis Toulon',
  'on regarde depuis Toulon',
  'team Toulon 👋',
  'ça vient de Toulon !',
  'hello depuis Toulon',
  'fan venu de Toulon',
  'Toulon représente !',
  'salut depuis Grenoble',
  'coucou de Grenoble',
  'Grenoble dans la place !',
  'présent depuis Grenoble',
  'on regarde depuis Grenoble',
  'team Grenoble 👋',
  'ça vient de Grenoble !',
  'hello depuis Grenoble',
  'fan venu de Grenoble',
  'Grenoble représente !',
  'coucou de Dijon',
  'Dijon dans la place !',
  'présent depuis Dijon',
  'on regarde depuis Dijon',
  'team Dijon 👋',
  'ça vient de Dijon !',
  'hello depuis Dijon',
  'fan venu de Dijon',
  'Dijon représente !',
  'coucou de Angers',
  'Angers dans la place !',
  'présent depuis Angers',
  'on regarde depuis Angers',
  'team Angers 👋',
  'ça vient de Angers !',
  'hello depuis Angers',
  'fan venu de Angers',
  'Angers représente !',
  'salut depuis Nîmes',
  'coucou de Nîmes',
  'Nîmes dans la place !',
  'présent depuis Nîmes',
  'on regarde depuis Nîmes',
  'team Nîmes 👋',
  'ça vient de Nîmes !',
  'hello depuis Nîmes',
  'fan venu de Nîmes',
  'Nîmes représente !',
  'salut depuis Villeurbanne',
  'coucou de Villeurbanne',
  'Villeurbanne dans la place !',
  'présent depuis Villeurbanne',
  'on regarde depuis Villeurbanne',
  'team Villeurbanne 👋',
  'ça vient de Villeurbanne !',
  'hello depuis Villeurbanne',
  'fan venu de Villeurbanne',
  'Villeurbanne représente !',
  'salut depuis Clermont-Ferrand',
  'coucou de Clermont-Ferrand',
  'Clermont-Ferrand dans la place !',
  'présent depuis Clermont-Ferrand',
  'on regarde depuis Clermont-Ferrand',
  'team Clermont-Ferrand 👋',
  'ça vient de Clermont-Ferrand !',
  'hello depuis Clermont-Ferrand',
  'fan venu de Clermont-Ferrand',
  'Clermont-Ferrand représente !',
  'salut depuis Le Mans',
  'coucou de Le Mans',
  'Le Mans dans la place !',
  'présent depuis Le Mans',
  'on regarde depuis Le Mans',
  'team Le Mans 👋',
  'ça vient de Le Mans !',
  'hello depuis Le Mans',
  'fan venu de Le Mans',
  'Le Mans représente !',
  'salut depuis Aix-en-Provence',
  'coucou de Aix-en-Provence',
  'Aix-en-Provence dans la place !',
  'présent depuis Aix-en-Provence',
  'on regarde depuis Aix-en-Provence',
  'team Aix-en-Provence 👋',
  'ça vient de Aix-en-Provence !',
  'hello depuis Aix-en-Provence',
  'fan venu de Aix-en-Provence',
  'Aix-en-Provence représente !',
  'salut depuis Brest',
  'coucou de Brest',
  'Brest dans la place !',
  'présent depuis Brest',
  'on regarde depuis Brest',
  'team Brest 👋',
  'ça vient de Brest !',
  'hello depuis Brest',
  'fan venu de Brest',
  'Brest représente !',
  'coucou de Tours',
  'Tours dans la place !',
  'présent depuis Tours',
  'on regarde depuis Tours',
  'team Tours 👋',
  'ça vient de Tours !',
  'hello depuis Tours',
  'fan venu de Tours',
  'Tours représente !',
  'salut depuis Limoges',
  'coucou de Limoges',
  'Limoges dans la place !',
  'présent depuis Limoges',
  'on regarde depuis Limoges',
  'team Limoges 👋',
  'ça vient de Limoges !',
  'hello depuis Limoges',
  'fan venu de Limoges',
  'Limoges représente !',
  'salut depuis Amiens',
  'coucou de Amiens',
  'Amiens dans la place !',
  'présent depuis Amiens',
  'on regarde depuis Amiens',
  'team Amiens 👋',
  'ça vient de Amiens !',
  'hello depuis Amiens',
  'fan venu de Amiens',
  'Amiens représente !',
  'salut depuis Annecy',
  'coucou de Annecy',
  'Annecy dans la place !',
  'présent depuis Annecy',
  'on regarde depuis Annecy',
  'team Annecy 👋',
  'ça vient de Annecy !',
  'hello depuis Annecy',
  'fan venu de Annecy',
  'Annecy représente !',
  'salut depuis Perpignan',
  'coucou de Perpignan',
  'Perpignan dans la place !',
  'présent depuis Perpignan',
  'on regarde depuis Perpignan',
  'team Perpignan 👋',
  'ça vient de Perpignan !',
  'hello depuis Perpignan',
  'fan venu de Perpignan',
  'Perpignan représente !',
  'salut depuis Metz',
  'coucou de Metz',
  'Metz dans la place !',
  'présent depuis Metz',
  'on regarde depuis Metz',
  'team Metz 👋',
  'ça vient de Metz !',
  'hello depuis Metz',
  'fan venu de Metz',
  'Metz représente !',
  'salut depuis Besançon',
  'coucou de Besançon',
  'Besançon dans la place !',
  'présent depuis Besançon',
  'on regarde depuis Besançon',
  'team Besançon 👋',
  'ça vient de Besançon !',
  'hello depuis Besançon',
  'fan venu de Besançon',
  'Besançon représente !',
  'salut depuis Orléans',
  'coucou de Orléans',
  'Orléans dans la place !',
  'présent depuis Orléans',
  'on regarde depuis Orléans',
  'team Orléans 👋',
  'ça vient de Orléans !',
  'hello depuis Orléans',
  'fan venu de Orléans',
  'Orléans représente !',
  'salut depuis Mulhouse',
  'coucou de Mulhouse',
  'Mulhouse dans la place !',
  'présent depuis Mulhouse',
  'on regarde depuis Mulhouse',
  'team Mulhouse 👋',
  'ça vient de Mulhouse !',
  'hello depuis Mulhouse',
  'fan venu de Mulhouse',
  'Mulhouse représente !',
  'salut depuis Rouen',
  'coucou de Rouen',
  'Rouen dans la place !',
  'présent depuis Rouen',
  'on regarde depuis Rouen',
  'team Rouen 👋',
  'ça vient de Rouen !',
  'hello depuis Rouen',
  'fan venu de Rouen',
  'Rouen représente !',
  'salut depuis Caen',
  'coucou de Caen',
  'Caen dans la place !',
  'présent depuis Caen',
  'on regarde depuis Caen',
  'team Caen 👋',
  'ça vient de Caen !',
  'hello depuis Caen',
  'fan venu de Caen',
  'Caen représente !',
  'salut depuis Nancy',
  'coucou de Nancy',
  'Nancy dans la place !',
  'présent depuis Nancy',
  'on regarde depuis Nancy',
  'team Nancy 👋',
  'ça vient de Nancy !',
  'hello depuis Nancy',
  'fan venu de Nancy',
  'Nancy représente !',
  'salut depuis Genève',
  'coucou de Genève',
  'Genève dans la place !',
  'présent depuis Genève',
  'on regarde depuis Genève',
  'team Genève 👋',
  'ça vient de Genève !',
  'hello depuis Genève',
  'fan venu de Genève',
  'Genève représente !',
  'salut depuis Bruxelles',
  'coucou de Bruxelles',
  'Bruxelles dans la place !',
  'présent depuis Bruxelles',
  'on regarde depuis Bruxelles',
  'team Bruxelles 👋',
  'ça vient de Bruxelles !',
  'hello depuis Bruxelles',
  'fan venu de Bruxelles',
  'Bruxelles représente !',
  'salut depuis Montréal',
  'coucou de Montréal',
  'Montréal dans la place !',
  'présent depuis Montréal',
  'on regarde depuis Montréal',
  'team Montréal 👋',
  'ça vient de Montréal !',
  'hello depuis Montréal',
  'fan venu de Montréal',
  'Montréal représente !',
  'salut depuis Québec',
  'coucou de Québec',
  'Québec dans la place !',
  'présent depuis Québec',
  'on regarde depuis Québec',
  'team Québec 👋',
  'ça vient de Québec !',
  'hello depuis Québec',
  'fan venu de Québec',
  'Québec représente !',
  'salut depuis Dakar',
  'coucou de Dakar',
  'Dakar dans la place !',
  'présent depuis Dakar',
  'on regarde depuis Dakar',
  'team Dakar 👋',
  'ça vient de Dakar !',
  'hello depuis Dakar',
  'fan venu de Dakar',
  'Dakar représente !',
  'salut depuis Abidjan',
  'coucou de Abidjan',
  'Abidjan dans la place !',
  'présent depuis Abidjan',
  'on regarde depuis Abidjan',
  'team Abidjan 👋',
  'ça vient de Abidjan !',
  'hello depuis Abidjan',
  'fan venu de Abidjan',
  'Abidjan représente !',
  'salut depuis Casablanca',
  'coucou de Casablanca',
  'Casablanca dans la place !',
  'présent depuis Casablanca',
  'on regarde depuis Casablanca',
  'team Casablanca 👋',
  'ça vient de Casablanca !',
  'hello depuis Casablanca',
  'fan venu de Casablanca',
  'Casablanca représente !',
  'salut depuis Tunis',
  'coucou de Tunis',
  'Tunis dans la place !',
  'présent depuis Tunis',
  'on regarde depuis Tunis',
  'team Tunis 👋',
  'ça vient de Tunis !',
  'hello depuis Tunis',
  'fan venu de Tunis',
  'Tunis représente !',
  'salut depuis Alger',
  'coucou de Alger',
  'Alger dans la place !',
  'présent depuis Alger',
  'on regarde depuis Alger',
  'team Alger 👋',
  'ça vient de Alger !',
  'hello depuis Alger',
  'fan venu de Alger',
  'Alger représente !',
  'salut depuis Beyrouth',
  'coucou de Beyrouth',
  'Beyrouth dans la place !',
  'présent depuis Beyrouth',
  'on regarde depuis Beyrouth',
  'team Beyrouth 👋',
  'ça vient de Beyrouth !',
  'hello depuis Beyrouth',
  'fan venu de Beyrouth',
  'Beyrouth représente !',
  'salut depuis Lausanne',
  'coucou de Lausanne',
  'Lausanne dans la place !',
  'présent depuis Lausanne',
  'on regarde depuis Lausanne',
  'team Lausanne 👋',
  'ça vient de Lausanne !',
  'hello depuis Lausanne',
  'fan venu de Lausanne',
  'Lausanne représente !',
  'salut depuis Liège',
  'coucou de Liège',
  'Liège dans la place !',
  'présent depuis Liège',
  'on regarde depuis Liège',
  'team Liège 👋',
  'ça vient de Liège !',
  'hello depuis Liège',
  'fan venu de Liège',
  'Liège représente !',
  'salut depuis Avignon',
  'coucou de Avignon',
  'Avignon dans la place !',
  'présent depuis Avignon',
  'on regarde depuis Avignon',
  'team Avignon 👋',
  'ça vient de Avignon !',
  'hello depuis Avignon',
  'fan venu de Avignon',
  'Avignon représente !',
  'salut depuis Pau',
  'coucou de Pau',
  'Pau dans la place !',
  'présent depuis Pau',
  'on regarde depuis Pau',
  'team Pau 👋',
  'ça vient de Pau !',
  'hello depuis Pau',
  'fan venu de Pau',
  'Pau représente !',
  '🔥🔥',
  '🔥❤️',
  '🔥😂',
  '🔥🎉',
  '🔥💯',
  '🔥😍',
  '🔥🥳',
  '🔥👀',
  '🔥🙌',
  '🔥💪',
  '🔥🚀',
  '🔥🌟',
  '🔥🤩',
  '🔥🥶',
  '🔥🤍',
  '🔥🌈',
  '🔥😇',
  '🔥🙏',
  '🔥🎯',
  '🔥🤗',
  '🔥🤝',
  '🔥🎶',
  '🔥😎',
  '🔥🥹',
  '🔥😤',
  '🔥🥇',
  '🔥✨',
  '🔥😱',
  '🔥🤤',
  '🔥😏',
  '🔥🥰',
  '🔥😆',
  '🔥🫡',
  '🔥🤌',
  '❤️🔥',
  '❤️😂',
  '❤️👏',
  '❤️🎉',
  '❤️💯',
  '❤️😍',
  '❤️🥳',
  '❤️👀',
  '❤️🙌',
  '❤️💪',
  '❤️🚀',
  '❤️🌟',
  '❤️🤩',
  '❤️🥶',
  '❤️🤍',
  '❤️🌈',
  '❤️😇',
  '❤️🙏',
  '❤️🎯',
  '❤️🤗',
  '❤️🤝',
  '❤️🎶',
  '❤️😎',
  '❤️🥹',
  '❤️😤',
  '❤️🥇',
  '❤️✨',
  '❤️😱',
  '❤️🤤',
  '❤️😏',
  '❤️🥰',
  '❤️😆',
  '❤️🫡',
  '❤️🤌',
  '😂🔥',
  '😂❤️',
  '😂😂',
  '😂👏',
  '😂🎉',
  '😂💯',
  '😂😍',
  '😂🥳',
  '😂👀',
  '😂🙌',
  '😂💪',
  '😂🚀',
  '😂🌟',
  '😂🤩',
  '😂🥶',
  '😂🤍',
  '😂🌈',
  '😂😇',
  '😂🙏',
  '😂🎯',
  '😂🤗',
  '😂🤝',
  '😂🎶',
  '😂😎',
  '😂🥹',
  '😂😤',
  '😂🥇',
  '😂✨',
  '😂😱',
  '😂🤤',
  '😂😏',
  '😂🥰',
  '😂😆',
  '😂🫡',
  '😂🤌',
  '👏🔥',
  '👏❤️',
  '👏😂',
  '👏👏',
  '👏🎉',
  '👏💯',
  '👏😍',
  '👏🥳',
  '👏👀',
  '👏🙌',
  '👏💪',
  '👏🚀',
  '👏🌟',
  '👏🤩',
  '👏🥶',
  '👏🤍',
  '👏🌈',
  '👏😇',
  '👏🙏',
  '👏🎯',
  '👏🤗',
  '👏🤝',
  '👏🎶',
  '👏😎',
  '👏🥹',
  '👏😤',
  '👏🥇',
  '👏✨',
  '👏😱',
  '👏🤤',
  '👏😏',
  '👏🥰',
  '👏😆',
  '👏🫡',
  '👏🤌',
  '🎉🔥',
  '🎉❤️',
  '🎉😂',
  '🎉👏',
  '🎉🎉',
  '🎉💯',
  '🎉😍',
  '🎉🥳',
  '🎉👀',
  '🎉🙌',
  '🎉💪',
  '🎉🚀',
  '🎉🌟',
  '🎉🤩',
  '🎉🥶',
  '🎉🤍',
  '🎉🌈',
  '🎉😇',
  '🎉🙏',
  '🎉🎯',
  '🎉🤗',
  '🎉🤝',
  '🎉🎶',
  '🎉😎',
  '🎉🥹',
  '🎉😤',
  '🎉🥇',
  '🎉✨',
  '🎉😱',
  '🎉🤤',
  '🎉😏',
  '🎉🥰',
  '🎉😆',
  '🎉🫡',
  '🎉🤌',
  '💯🔥',
  '💯❤️',
  '💯😂',
  '💯👏',
  '💯🎉',
  '💯😍',
  '💯🥳',
  '💯👀',
  '💯🙌',
  '💯💪',
  '💯🚀',
  '💯🌟',
  '💯🤩',
  '💯🥶',
  '💯🤍',
  '💯🌈',
  '💯😇',
  '💯🙏',
  '💯🎯',
  '💯🤗',
  '💯🤝',
  '💯🎶',
  '💯😎',
  '💯🥹',
  '💯😤',
  '💯🥇',
  '💯✨',
  '💯😱',
  '💯🤤',
  '💯😏',
  '💯🥰',
  '💯😆',
  '💯🫡',
  '💯🤌',
  '😍🔥',
  '😍❤️',
  '😍😂',
  '😍👏',
  '😍🎉',
  '😍💯',
  '😍😍',
  '😍🥳',
  '😍👀',
  '😍🙌',
  '😍💪',
  '😍🚀',
  '😍🌟',
  '😍🤩',
  '😍🥶',
  '😍🤍',
  '😍🌈',
  '😍😇',
  '😍🙏',
  '😍🎯',
  '😍🤗',
  '😍🤝',
  '😍🎶',
  '😍😎',
  '😍🥹',
  '😍😤',
  '😍🥇',
  '😍✨',
  '😍😱',
  '😍🤤',
  '😍😏',
  '😍🥰',
  '😍😆',
  '😍🫡',
  '😍🤌',
  '🥳🔥',
  '🥳❤️',
  '🥳😂',
  '🥳👏',
  '🥳🎉',
  '🥳💯',
  '🥳😍',
  '🥳🥳',
  '🥳👀',
  '🥳🙌',
  '🥳💪',
  '🥳🚀',
  '🥳🌟',
  '🥳🤩',
  '🥳🥶',
  '🥳🤍',
  '🥳🌈',
  '🥳😇',
  '🥳🙏',
  '🥳🎯',
  '🥳🤗',
  '🥳🤝',
  '🥳🎶',
  '🥳😎',
  '🥳🥹',
  '🥳😤',
  '🥳🥇',
  '🥳✨',
  '🥳😱',
  '🥳🤤',
  '🥳😏',
  '🥳🥰',
  '🥳😆',
  '🥳🫡',
  '🥳🤌',
  '👀🔥',
  '👀❤️',
  '👀😂',
  '👀👏',
  '👀🎉',
  '👀💯',
  '👀😍',
  '👀🥳',
  '👀🙌',
  '👀💪',
  '👀🚀',
  '👀🌟',
];

const heartEmojis = ['❤️', '🧡', '💛', '💖', '💗', '💜', '🤍'];
